/** @type {import("./samplePanelSpec").samplePanelSpec | any} */
export const samplePanelSpecMirroredMood = {
  panelId: "mirrored_mood_panel_v1",
  title: "Visual panels",
  description: "PanelSpec -> source_data -> mirrored chart preview",
  panelKind: "mixed",
  intentType: "data",
  origin: "static",
  persistence: "temporary",
  sections: [
    {
      sectionId: "layout_primary",
      title: "Layout",
      priority: "primary",
      controls: [
        {
          id: "aspect_ratio",
          label: "Aspect Ratio",
          description: "Macro layout control for width/height related values",
          controlType: "select",
          operationType: "update",
          bindingMode: "multi",
          bind: "source_data.meta.aspectRatioPreset",
          binds: [
            "source_data.layout.svgWidth",
            "source_data.layout.svgHeight",
            "source_data.layout.chartBottom",
            "source_data.layout.titleY",
            "source_data.layout.subtitleY",
          ],
          options: [
            {
              label: "420 x 520 (Original)",
              value: "420x520",
              patch: {
                "source_data.layout.svgWidth": 420,
                "source_data.layout.svgHeight": 520,
                "source_data.layout.chartBottom": 382,
                "source_data.layout.titleY": 438,
                "source_data.layout.subtitleY": 488,
              },
            },
            {
              label: "480 x 560 (Balanced)",
              value: "480x560",
              patch: {
                "source_data.layout.svgWidth": 480,
                "source_data.layout.svgHeight": 560,
                "source_data.layout.chartBottom": 410,
                "source_data.layout.titleY": 470,
                "source_data.layout.subtitleY": 520,
              },
            },
            {
              label: "540 x 600 (Wide)",
              value: "540x600",
              patch: {
                "source_data.layout.svgWidth": 540,
                "source_data.layout.svgHeight": 600,
                "source_data.layout.chartBottom": 438,
                "source_data.layout.titleY": 510,
                "source_data.layout.subtitleY": 560,
              },
            },
          ],
          expandable: true,
          detailSectionRef: "layout_detail",
          impactPolicy: "mixed",
          impactDescription: "This control updates multiple layout fields together.",
        },
      ],
    },
    {
      sectionId: "layout_detail",
      title: "Layout Detail",
      priority: "detail",
      controls: [
        {
          id: "svg_width",
          label: "SVG Width",
          controlType: "number",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.svgWidth",
          valueType: "number",
          range: { min: 280, max: 1200, step: 10 },
        },
        {
          id: "svg_height",
          label: "SVG Height",
          controlType: "number",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.svgHeight",
          valueType: "number",
          range: { min: 320, max: 1200, step: 10 },
        },
        {
          id: "chart_top",
          label: "Chart Top",
          controlType: "number",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.chartTop",
          valueType: "number",
          range: { min: 0, max: 480, step: 1 },
        },
        {
          id: "chart_bottom",
          label: "Chart Bottom",
          controlType: "number",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.chartBottom",
          valueType: "number",
          range: { min: 100, max: 900, step: 1 },
        },
        {
          id: "bar_height",
          label: "Bar Height",
          controlType: "slider",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.barHeight",
          valueType: "number",
          range: { min: 6, max: 40, step: 1 },
        },
        {
          id: "label_gap",
          label: "Center Label Gap",
          controlType: "slider",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.labelGap",
          valueType: "number",
          range: { min: 18, max: 180, step: 1 },
        },
        {
          id: "value_pad",
          label: "Value Pad",
          controlType: "slider",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.valuePad",
          valueType: "number",
          range: { min: 0, max: 24, step: 1 },
        },
      ],
    },
    {
      sectionId: "theme_primary",
      title: "Color Theme",
      priority: "primary",
      controls: [
        {
          id: "color_theme",
          label: "Color Theme",
          controlType: "preset-select",
          operationType: "update",
          bindingMode: "preset",
          presetOptions: [
            {
              id: "original",
              label: "Original Warm",
              patch: {
                "source_data.style.waitingAreaColor": "#c75b4e",
                "source_data.style.corridorColor": "#efc45a",
                "source_data.style.titleColor": "#3f3f3f",
                "source_data.style.subtitleColor": "#808080",
                "source_data.style.textMidColor": "#666666",
                "source_data.style.textLightColor": "#7a7a7a",
              },
            },
            {
              id: "ocean",
              label: "Ocean Calm",
              patch: {
                "source_data.style.waitingAreaColor": "#2563eb",
                "source_data.style.corridorColor": "#38bdf8",
                "source_data.style.titleColor": "#0f172a",
                "source_data.style.subtitleColor": "#334155",
                "source_data.style.textMidColor": "#475569",
                "source_data.style.textLightColor": "#64748b",
              },
            },
            {
              id: "forest",
              label: "Forest",
              patch: {
                "source_data.style.waitingAreaColor": "#047857",
                "source_data.style.corridorColor": "#84cc16",
                "source_data.style.titleColor": "#14532d",
                "source_data.style.subtitleColor": "#3f6212",
                "source_data.style.textMidColor": "#365314",
                "source_data.style.textLightColor": "#4d7c0f",
              },
            },
          ],
          expandable: true,
          detailSectionRef: "theme_detail",
          impactPolicy: "mixed",
          impactDescription: "Preset applies a multi-field style patch instantly.",
        },
      ],
    },
    {
      sectionId: "theme_detail",
      title: "Theme Detail",
      priority: "detail",
      controls: [
        {
          id: "waiting_color",
          label: "Waiting Area Color",
          controlType: "color",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.style.waitingAreaColor",
          valueType: "color",
        },
        {
          id: "corridor_color",
          label: "Corridor Color",
          controlType: "color",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.style.corridorColor",
          valueType: "color",
        },
        {
          id: "title_color",
          label: "Title Color",
          controlType: "color",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.style.titleColor",
          valueType: "color",
        },
        {
          id: "subtitle_color",
          label: "Subtitle Color",
          controlType: "color",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.style.subtitleColor",
          valueType: "color",
        },
      ],
    },
    {
      sectionId: "data_table",
      title: "Data Table",
      priority: "primary",
      controls: [
        {
          id: "table_orientation",
          label: "Table Orientation",
          controlType: "select",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.meta.tableOrientation",
          options: [
            { label: "Row Major", value: "row-major" },
            { label: "Column Major", value: "column-major" },
          ],
        },
        {
          id: "mood_data_table",
          label: "Mood Data",
          controlType: "table",
          operationType: "update",
          bindingMode: "collection",
          targetCollection: "source_data.data",
          rowKey: "month",
          rowActions: ["add", "remove"],
          schemaSource: "mixed",
          tableOrientation: "auto",
          orientationKey: "source_data.meta.tableOrientation",
          tableSchema: [
            { key: "month", label: "Month", valueType: "string", editable: true },
            { key: "waitingArea", label: "Waiting Area", valueType: "number", editable: true },
            { key: "corridor", label: "Corridor", valueType: "number", editable: true },
          ],
          initialValue: {
            month: "2024-01",
            waitingArea: 9.1,
            corridor: 8.8,
          },
        },
      ],
    },
    {
      sectionId: "data_layout_policy",
      title: "Data Layout Policy",
      priority: "secondary",
      controls: [
        {
          id: "fixed_chart_size",
          label: "Fixed Chart Size",
          description: "When true, row spacing auto-fits data length.",
          controlType: "toggle",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.fixedChartSize",
          valueType: "boolean",
        },
        {
          id: "policy_chart_top",
          label: "Chart Top",
          controlType: "number",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.chartTop",
          valueType: "number",
          range: { min: 0, max: 480, step: 1 },
          visibilityCondition: {
            path: "source_data.layout.fixedChartSize",
            equals: false,
          },
        },
        {
          id: "policy_chart_bottom",
          label: "Chart Bottom",
          controlType: "number",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.chartBottom",
          valueType: "number",
          range: { min: 100, max: 900, step: 1 },
          visibilityCondition: {
            path: "source_data.layout.fixedChartSize",
            equals: false,
          },
        },
        {
          id: "policy_bar_height",
          label: "Bar Height",
          controlType: "slider",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.barHeight",
          valueType: "number",
          range: { min: 6, max: 40, step: 1 },
          visibilityCondition: {
            path: "source_data.layout.fixedChartSize",
            equals: false,
          },
        },
        {
          id: "policy_label_gap",
          label: "Label Gap",
          controlType: "slider",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.labelGap",
          valueType: "number",
          range: { min: 18, max: 180, step: 1 },
          visibilityCondition: {
            path: "source_data.layout.fixedChartSize",
            equals: false,
          },
        },
        {
          id: "policy_row_step",
          label: "Row Step",
          controlType: "slider",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.layout.rowStep",
          valueType: "number",
          range: { min: 14, max: 80, step: 0.5 },
          visibilityCondition: {
            path: "source_data.layout.fixedChartSize",
            equals: false,
          },
        },
      ],
    },
    {
      sectionId: "legend_primary",
      title: "Legend",
      priority: "primary",
      controls: [
        {
          id: "legend_font_size",
          label: "Legend Font Size",
          controlType: "number",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.legend.legendFontSize",
          valueType: "number",
          range: { min: 9, max: 24, step: 1 },
        },
        {
          id: "legend_position",
          label: "Legend Position",
          controlType: "select",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.legend.legendPosition",
          options: [
            { label: "Top Center", value: "top-center" },
            { label: "Top Left", value: "top-left" },
            { label: "Top Right", value: "top-right" },
          ],
        },
        {
          id: "legend_direction",
          label: "Legend Direction",
          controlType: "select",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.legend.legendDirection",
          options: [
            { label: "Horizontal", value: "horizontal" },
            { label: "Vertical", value: "vertical" },
          ],
          expandable: true,
          detailSectionRef: "legend_detail",
        },
      ],
    },
    {
      sectionId: "legend_detail",
      title: "Legend Items Detail",
      priority: "detail",
      controls: [
        {
          id: "legend_items_table",
          label: "Legend Items",
          controlType: "table",
          operationType: "update",
          bindingMode: "collection",
          targetCollection: "source_data.legend.legendItems",
          rowKey: "id",
          rowActions: ["add", "remove"],
          schemaSource: "mixed",
          tableOrientation: "row-major",
          tableSchema: [
            { key: "id", label: "ID", valueType: "string", editable: true },
            { key: "label", label: "Label", valueType: "string", editable: true },
            { key: "color", label: "Color", valueType: "color", editable: true },
          ],
          initialValue: {
            id: "item_new",
            label: "New Item",
            color: "#64748b",
          },
        },
      ],
    },
    {
      sectionId: "title_subtitle",
      title: "Title & Subtitle",
      priority: "primary",
      controls: [
        {
          id: "title_font_size",
          label: "Title Font Size",
          controlType: "number",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.title.titleFontSize",
          valueType: "number",
          range: { min: 10, max: 48, step: 1 },
        },
        {
          id: "subtitle_font_size",
          label: "Subtitle Font Size",
          controlType: "number",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.title.subtitleFontSize",
          valueType: "number",
          range: { min: 8, max: 28, step: 1 },
        },
        {
          id: "title_color_repeat",
          label: "Title Color",
          controlType: "color",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.style.titleColor",
          valueType: "color",
        },
        {
          id: "subtitle_color_repeat",
          label: "Subtitle Color",
          controlType: "color",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.style.subtitleColor",
          valueType: "color",
        },
        {
          id: "title_line_1",
          label: "Title Line 1",
          controlType: "text",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.title.titleLines.0",
          valueType: "string",
        },
        {
          id: "title_line_2",
          label: "Title Line 2",
          controlType: "text",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.title.titleLines.1",
          valueType: "string",
        },
        {
          id: "subtitle_line_1",
          label: "Subtitle Line 1",
          controlType: "text",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.title.subtitleLines.0",
          valueType: "string",
        },
        {
          id: "subtitle_line_2",
          label: "Subtitle Line 2",
          controlType: "text",
          operationType: "update",
          bindingMode: "single",
          bind: "source_data.title.subtitleLines.1",
          valueType: "string",
        },
      ],
    },
  ],
};
