function safeJson(value) {
  try {
    return JSON.stringify(value, null, 2);
  } catch (error) {
    return "{}";
  }
}

export function buildIntentPrompt({ prompt, context }) {
  const schemaText = `{
  "User_prompt": "string",
  "target": "data | style | other",
  "action": "add | remove | update",
  "expand": true,
  "parameters": {
    "some_parameter_name": "Recommendation | Preset | None"
  }
}`;

  return [
    "You are an intent parser for a chart editing system.",
    "Return JSON ONLY. No markdown, no explanation.",
    "Output must strictly follow this schema:",
    schemaText,
    "",
    "Hard constraints:",
    "- target must be exactly one of: data, style, other.",
    "- action must be exactly one of: add, remove, update.",
    "- expand must be boolean.",
    "- parameters keys are generated by the model.",
    "- each parameters value must be exactly one of: Recommendation, Preset, None.",
    "- do not output any additional top-level fields.",
    "",
    "Semantic constraints:",
    "- data means values, records, and text content related edits.",
    "- style means width/height/color/shape visual edits.",
    "- other is only for upload image/SVG like special inputs.",
    "- expand only indicates whether high-level controls are insufficient and should be expanded later.",
    "- expand does NOT indicate code field extraction.",
    "",
    "Upload image/SVG rule:",
    "- target = other",
    "- action = add",
    "- expand = false",
    '- parameters = { "Input": "None" }',
    "",
    "Editor context:",
    safeJson(context || {}),
    "",
    "User prompt:",
    String(prompt || ""),
  ].join("\n");
}

