function safeString(value) {
  return String(value || "").trim();
}

function safeArray(value) {
  return Array.isArray(value) ? value : [];
}

function safeObject(value) {
  return value && typeof value === "object" && !Array.isArray(value) ? value : {};
}

function normalizeType(rawType, rawValue) {
  const type = safeString(rawType).toLowerCase();
  if (type.includes("color")) {
    return { controlType: "color", valueType: "color" };
  }
  if (type.includes("number") || type.includes("int") || type.includes("float")) {
    return { controlType: "number", valueType: "number" };
  }
  if (type.includes("bool")) {
    return { controlType: "toggle", valueType: "boolean" };
  }

  if (typeof rawValue === "number") {
    return { controlType: "number", valueType: "number" };
  }
  if (typeof rawValue === "boolean") {
    return { controlType: "toggle", valueType: "boolean" };
  }
  if (typeof rawValue === "string" && /^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i.test(rawValue.trim())) {
    return { controlType: "color", valueType: "color" };
  }

  return { controlType: "text", valueType: "string" };
}

function normalizeValue(value, valueType) {
  if (valueType === "number") {
    const n = Number(value);
    return Number.isFinite(n) ? n : 0;
  }
  if (valueType === "color") {
    const text = safeString(value);
    return /^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i.test(text) ? text : "#000000";
  }
  if (valueType === "boolean") {
    return Boolean(value);
  }
  if (value == null) {
    return "";
  }
  return typeof value === "string" ? value : String(value);
}

function toControlId(prefix, path, index) {
  const pathKey = safeString(path)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return `${prefix}_${pathKey || `item_${index + 1}`}`;
}

function buildSingleControl(item, index, idPrefix) {
  const path = safeString(item?.path);
  if (!path) {
    return null;
  }

  const title = safeString(item?.title || item?.name || path);
  const { controlType, valueType } = normalizeType(item?.type, item?.value);

  const control = {
    id: toControlId(idPrefix, path, index),
    label: title || path,
    controlType,
    operationType: "update",
    bindingMode: "single",
    bind: path,
    valueType,
    defaultValue: normalizeValue(item?.value, valueType),
  };

  if (item?.reason) {
    control.warningMessage = safeString(item.reason);
  }

  return control;
}

function buildPresetControl(recommendationJson, panelJson) {
  const presets = safeArray(recommendationJson?.presets);
  if (!presets.length) {
    return null;
  }

  const topPanel = safeObject(panelJson?.["top-panel"]);
  const topTitle = safeString(topPanel.title) || "Recommendation Presets";
  const presetOptions = presets
    .map((preset, index) => {
      const values = safeArray(preset?.values);
      const patch = {};
      values.forEach((item) => {
        const path = safeString(item?.path);
        if (!path) {
          return;
        }
        const mappedType = normalizeType(item?.type, item?.value);
        patch[path] = normalizeValue(item?.value, mappedType.valueType);
      });
      if (!Object.keys(patch).length) {
        return null;
      }
      return {
        id: safeString(preset?.id) || `preset_${index + 1}`,
        label: safeString(preset?.label) || `Preset ${index + 1}`,
        patch,
      };
    })
    .filter(Boolean);

  if (!presetOptions.length) {
    return null;
  }

  return {
    id: "recommendation_preset_select",
    label: topTitle,
    description: "Apply recommended style preset generated by model.",
    controlType: "preset-select",
    operationType: "update",
    bindingMode: "preset",
    presetOptions,
  };
}

function dedupeByPath(items) {
  const seen = new Set();
  return items.filter((item) => {
    const path = safeString(item?.path);
    if (!path || seen.has(path)) {
      return false;
    }
    seen.add(path);
    return true;
  });
}

function resolveSubPanelItems(recommendationJson, panelJson) {
  const fromPanelOutput = safeArray(panelJson?.["sub-panel"]);
  if (fromPanelOutput.length) {
    return dedupeByPath(fromPanelOutput);
  }
  const fromPanelInput = safeArray(recommendationJson?.structure?.attributes);
  return dedupeByPath(fromPanelInput);
}

function resolveAffectedItems(recommendationJson, panelJson) {
  const fromPanelOutput = safeArray(panelJson?.["affected-panel"]);
  if (fromPanelOutput.length) {
    return dedupeByPath(fromPanelOutput);
  }
  const fromPanelInput = safeArray(recommendationJson?.structure?.affected);
  return dedupeByPath(fromPanelInput);
}

function createSection(sectionId, title, priority = "primary") {
  return {
    type: "create-section",
    payload: {
      sectionId,
      title,
      priority,
      controls: [],
    },
  };
}

export function buildRecommendationPanelPlan({ recommendationJson, panelJson }) {
  const safeRecommendation = safeObject(recommendationJson);
  const safePanelJson = safeObject(panelJson);

  const subPanelItems = resolveSubPanelItems(safeRecommendation, safePanelJson);
  const affectedItems = resolveAffectedItems(safeRecommendation, safePanelJson);
  const presetControl = buildPresetControl(safeRecommendation, safePanelJson);

  const panelUpdates = [];

  if (presetControl) {
    panelUpdates.push(createSection("recommendation_presets", "Recommendation Presets", "primary"));
    panelUpdates.push({
      type: "insert-control",
      sectionId: "recommendation_presets",
      payload: presetControl,
    });
    panelUpdates.push({ type: "highlight-section", sectionId: "recommendation_presets" });
  }

  if (subPanelItems.length) {
    panelUpdates.push(createSection("recommendation_sub_panel", "Recommendation Controls", "primary"));
    subPanelItems.forEach((item, index) => {
      const control = buildSingleControl(item, index, "recommendation_sub");
      if (!control) {
        return;
      }
      panelUpdates.push({
        type: "insert-control",
        sectionId: "recommendation_sub_panel",
        payload: control,
      });
    });
  }

  if (affectedItems.length) {
    panelUpdates.push(createSection("recommendation_affected_panel", "Affected Controls", "detail"));
    affectedItems.forEach((item, index) => {
      const control = buildSingleControl(item, index, "recommendation_affected");
      if (!control) {
        return;
      }
      panelUpdates.push({
        type: "insert-control",
        sectionId: "recommendation_affected_panel",
        payload: control,
      });
    });
    panelUpdates.push({ type: "expand-section", sectionId: "recommendation_affected_panel" });
  }

  return {
    sourceDataUpdates: [],
    panelUpdates,
  };
}
